[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "your_supabase_url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  NEXT_PUBLIC_GEMINI_API_KEY = "your_gemini_api_key"

[[plugins]]
  package = "@netlify/plugin-nextjs"